# This config should be placed in following path:
#   %AppData%\Parity\Ethereum\config.toml

[parity]
# Auto-updates to every release.
auto_update = "all"
# Ropsten Test Network
chain = "ropsten"
# Parity databases will be stored in D:\parity\ropsten.
#db_path = "D:\\parity\\ropsten"

[network]
# Override the bootnodes from selected chain file.
bootnodes = ["enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303", "enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"]

[rpc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore", "personal", "parity_accounts"]

[websockets]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "parity_pubsub", "traces", "rpc", "secretstore", "personal", "parity_accounts"]

[ipc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "parity_accounts", "parity_pubsub", "traces", "rpc", "secretstore", "personal"]